In [1]:
import tensorflow as tf
from tensorflow import keras
import pathlib
import numpy as np

# Cambiar rutas para poder probar un dataset cualquiera
test_dir = r"C:\dataset_img_mask\test"

IMG_SIZE = (128, 128) 
BATCH_SIZE = 32

dataset = keras.utils.image_dataset_from_directory(
    test_dir,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    label_mode="binary"
)

Found 160 files belonging to 2 classes.


In [2]:
print("\n--- Tipo de Dataset ---")
print(type(dataset))

print("\n--- Elementos del Dataset ---")
for elem in dataset:
    print(elem)


--- Tipo de Dataset ---
<class 'tensorflow.python.data.ops.prefetch_op._PrefetchDataset'>

--- Elementos del Dataset ---
(<tf.Tensor: shape=(32, 128, 128, 3), dtype=float32, numpy=
array([[[[166.3086    , 154.27296   , 150.48047   ],
         [182.99077   , 150.68999   , 151.68999   ],
         [186.93442   , 136.60712   , 135.92506   ],
         ...,
         [235.45786   , 244.71957   , 191.7758    ],
         [235.29155   , 247.64702   , 194.0767    ],
         [242.69531   , 253.2075    , 198.74562   ]],

        [[161.93466   , 155.29688   , 149.0728    ],
         [177.52734   , 146.22656   , 143.5973    ],
         [183.88034   , 130.28268   , 127.731186  ],
         ...,
         [236.41087   , 244.24219   , 195.74681   ],
         [238.05539   , 247.05539   , 202.63351   ],
         [239.68892   , 248.68892   , 204.26704   ]],

        [[160.96094   , 153.65234   , 148.5187    ],
         [182.19675   , 148.47656   , 141.59056   ],
         [177.63672   , 121.644745  , 114.77

In [3]:
print("\n--- Primer elemento del Dataset ---")
print(dataset.take(1))


--- Primer elemento del Dataset ---
<_TakeDataset element_spec=(TensorSpec(shape=(None, 128, 128, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None, 1), dtype=tf.float32, name=None))>


In [6]:
# Inspeccionar el primer batch (el dataset contiene varios batches... con tamaño especificado arriba)
print("\n--- Primer Batch de Imágenes ---")
for batch, labels in dataset.take(1):
    print("Forma del batch:", batch.shape)
    print("Etiquetas:", labels) # labels.numpy() convierte de tf.Tensor a array de Numpy


--- Primer Batch de Imágenes ---
Forma del batch: (32, 128, 128, 3)
Etiquetas: tf.Tensor(
[[0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]], shape=(32, 1), dtype=float32) 

In [8]:
# Obtener tamaño del dataset
dataset_size = dataset.reduce(0, lambda x, _: x + 1).numpy()
print(f"\n--- Tamaño del Dataset (en batches...): {dataset_size} ---")


--- Tamaño del Dataset (en batches...): 5 ---


In [9]:
# Ver la estructura del dataset (MUY IMPORTANTE)
print("\n--- Estructura de los elementos ---")
print(dataset.element_spec)


--- Estructura de los elementos ---
(TensorSpec(shape=(None, 128, 128, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None, 1), dtype=tf.float32, name=None))


In [11]:
# Ejemplo para visualizar las dimensiones totales (en este ejemplo el tensor principal tiene 5 dim)
data_numpy = np.array([x.numpy() for x, y in dataset])
labels_numpy = np.array([y.numpy() for x, y in dataset])

print("Forma de los datos (NumPy):", data_numpy.shape)
print("Forma de las etiquetas en NumPy:", labels_numpy.shape)

Forma de los datos en NumPy: (5, 32, 128, 128, 3)
Forma de las etiquetas en NumPy: (5, 32, 1)


In [13]:
# Ejemplo para inspeccionar las dimensiones que tiene 1 batch
for x_batch, y_batch in dataset.take(1):  # Desempaquetar la tupla
    print("Forma de un batch de imágenes:", x_batch.shape)
    print("Forma de un batch de etiquetas:", y_batch.shape)

Forma de un batch de imágenes: (32, 128, 128, 3)
Forma de un batch de etiquetas: (32, 1)
